/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#44474b',
        'primary-fixed': '#ffd9df',
        'inverse-on-surface': '#f1f1f1',
        'secondary-fixed-dim': '#ffb68b',
        'on-tertiary-fixed': '#191c1f',
        'surface-container-high': '#e8e8e8',
        'outline': '#897175',
        'on-secondary': '#ffffff',
        'on-surface': '#1a1c1c',
        'tertiary-container': '#45484c',
        'primary-container': '#861f41',
        'on-background': '#1a1c1c',
        'surface-container': '#eeeeee',
        'inverse-surface': '#2f3131',
        'tertiary-fixed': '#e0e2e7',
        'secondary-container': '#ff8934',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary': '#67022b',
        'on-tertiary-container': '#b4b7bb',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#851e40',
        'on-primary-container': '#ff99b0',
        'tertiary-fixed-dim': '#c4c6cb',
        'inverse-primary': '#ffb1c1',
        'secondary': '#994700',
        'surface': '#f9f9f9',
        'on-surface-variant': '#564245',
        'background': '#f9f9f9',
        'on-secondary-fixed-variant': '#743400',
        'surface-tint': '#a43757',
        'outline-variant': '#dcc0c4',
        'on-secondary-container': '#662d00',
        'error': '#ba1a1a',
        'surface-dim': '#dadada',
        'secondary-fixed': '#ffdbc8',
        'on-secondary-fixed': '#321300',
        'surface-bright': '#f9f9f9',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-variant': '#e2e2e2',
        'primary-fixed-dim': '#ffb1c1',
        'on-primary-fixed': '#3f0017',
        'tertiary': '#2e3235',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
